services:
    app:
        build: .
        container_name: feedops_app
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
            - redis
        ports:
            - "8080:8080"
        tty: true # keeps log output readable
